spring:
  application:
    name: config
  output:
    ansi:
      enabled: always
  profiles:
    active: native
server:
  port: 8768
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

