spring:
  application:
    name: service-loadbalance
server:
  port: 8765
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
