spring:
  application:
    name: service-order
server:
  port: 8762
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
